version: '3'

volumes:
  db:
  deps:
  build:
  node_modules:
  yarn-cache:

services:
  db:
    image: postgres:10
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: mix phx.server
    depends_on:
      - db
    working_dir: /app
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'build:/app/_build'
    environment:
      DATABASE_HOST: db
      HTTP_PORT: 80
      TERM: xterm
    ports:
      - 4000:80

  ngrok:
    image: wernight/ngrok
    ports:
      - 4041:4040
    environment:
      NGROK_PORT: 'app:80'

  node:
    image: node:9.1
    command: yarn start
    depends_on:
      - app
    working_dir: /app
    volumes:
      - './assets/aida_web:/app'
      - 'node_modules:/app/node_modules'
      - 'yarn-cache:/usr/local/share/.cache/yarn'
    environment:
      REACT_APP_API_BASE_URL: http://app.aida.dev
    ports:
      - 3000:3000
