version: '3'

volumes:
  db:
  deps:
  build:

services:
  db:
    image: postgres:10
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    command: mix phx.server
    depends_on:
      - db
    working_dir: /app
    volumes:
      - './:/app'
      - 'deps:/app/deps'
      - 'build:/app/_build'
    environment:
      DATABASE_HOST: db
      HTTP_PORT: 80
      TERM: xterm
    ports:
      - 4000:80

  ngrok:
    image: wernight/ngrok
    ports:
      - 4041:4040
    environment:
      NGROK_PORT: 'app:80'
